### ISSUE TITLE
Docker container is unavailable

### ISSUE THREAD

**Issue by pro100vald** [badboysm890/ClaraVerse#56]
It seems like docker container version of this app is not available to public, or at least is not pullable from linux. 

```
root@server:~# docker run -d --name clara --pull always -p 8100:8000 ghcr.io/badboysm890/claraverse       
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```

**Comment by badboysm890** [comment]
I will push an build for linux now and update soon

**Comment by badboysm890** [comment]
I have pushed an Appimage and deb for linux you can check that out should be easy that way

**Comment by pro100vald** [comment]
Still unable to pull the image. I've decided to test this with my main pc too.
Windows 11:
```
PS C:\Users\user> docker run -d --name clara --pull always -p 8100:8000 ghcr.io/badboysm890/claraverse:latest
docker: Error response from daemon: failed to resolve reference "ghcr.io/badboysm890/claraverse:latest": ghcr.io/badboysm890/claraverse:latest: not found.
See 'docker run --help'.
```
Debian 12:
```
root@server:~# docker run -d --name clara --pull always -p 8100:8000 ghcr.io/badboysm890/claraverse:latest
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```
However, this is what happens if I logout from ghcr.io:
```
root@server:~# docker logout ghcr.io 
Removing login credentials for ghcr.io
root@server:~# docker run -d --name clara --pull always -p 8100:8000 ghcr.io/badboysm890/claraverse:latest
docker: Error response from daemon: Head "https://ghcr.io/v2/badboysm890/claraverse/manifests/latest": denied.
See 'docker run --help'.
```
I strongly suspect that your container repo isn't public; that would explain why without credentials I get a "denied" responce, but with credentials I get a "not found" error.

**Comment by erygvy** [comment]
issue for me as well

**Comment by badboysm890** [comment]
we are planning to release a complete different repo for this specifically. will update regarding this
